
title: The homepage of Dr. Xi Chen
subtitle: Welcome to visit our lab
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: XI CHEN
email: xchen@geo.ecnu.edu.cn

# You'll want to customize url and baseurl for your own site:
baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
